// BASIC LATIN (U+0020..U+007E) from KiCad newstroke_font.cpp
// Copyright KiCad Developers; GPL-2.0-or-later (same glyphs KiCad plots).
pub const GLYPHS: [&str; 95] = [
    "JZ", // 32 SPC
    "MWRYSZR[QZRYR[ RRSQGRFSGRSRF", // 33 !
    "JZNFNJ RVFVJ", // 34 "
    "H]LM[M RRDL_ RS_YD RYVJV", // 35 #
    "H\\LZO[T[VZWYXWXUWSVRTQPPNOMNLLLJMHNGPFUFXG RRCR^", // 36 $
    "F^J[ZF RMFOGPIOKMLKKJIKGMF RYZZXYVWUUVTXUZW[YZ", // 37 %
    "E_[[Z[XZUWPQNNMKMINGPFQFSGTITJSLRMLQKRJTJWKYLZN[Q[SZTYWUXRXP", // 38 &
    "MWSFQJ", // 39 '
    "KYVcUbS_R]QZPUPQQLRISGUDVC", // 40 (
    "KYNcObQ_R]SZTUTQSLRIQGODNC", // 41 )
    "JZMIRKWI ROORKUO RRFRK", // 42 *
    "E_JSZS RR[RK", // 43 +
    "MWSZS[R]Q^", // 44 ,
    "E_JSZS", // 45 -
    "MWRYSZR[QZRYR[", // 46 .
    "G][EI`", // 47 /
    "H\\QFSFUGVHWJXNXSWWVYUZS[Q[OZNYMWLSLNMJNHOGQF", // 48 0
    "H\\X[L[ RR[RFPINKLL", // 49 1
    "H\\LHMGOFTFVGWHXJXLWOK[X[", // 50 2
    "H\\KFXFQNTNVOWPXRXWWYVZT[N[LZKY", // 51 3
    "H\\VMV[ RQELTYT", // 52 4
    "H\\WFMFLPMOONTNVOWPXRXWWYVZT[O[MZLY", // 53 5
    "H\\VFRFPGOHMKLOLWMYNZP[T[VZWYXWXRWPVOTNPNNOMPLR", // 54 6
    "H\\KFYFP[", // 55 7
    "H\\PONNMMLKLJMHNGPFTFVGWHXJXKWMVNTOPONPMQLSLWMYNZP[T[VZWYXWXSWQVPTO", // 56 8
    "H\\N[R[TZUYWVXRXJWHVGTFPFNGMHLJLOMQNRPSTSVRWQXO", // 57 9
    "MWRYSZR[QZRYR[ RRNSORPQORNRP", // 58 :
    "MWSZS[R]Q^ RRNSORPQORNRP", // 59 ;
    "E_ZMJSZY", // 60 <
    "E_JPZP RZVJV", // 61 =
    "E_JMZSJY", // 62 >
    "I[QYRZQ[PZQYQ[ RMGOFTFVGWIWKVMUNSORPQRQS", // 63 ?
    "D_VQUPSOQOOPNQMSMUNWOXQYSYUXVW RVOVWWXXXZW[U[PYMVKRJNKKMIPHTIXK[N]R^V]Y[", // 64 @
    "I[MUWU RK[RFY[", // 65 A
    "G\\SPVQWRXTXWWYVZT[L[LFSFUGVHWJWLVNUOSPLP", // 66 B
    "F[WYVZS[Q[NZLXKVJRJOKKLINGQFSFVGWH", // 67 C
    "G\\L[LFQFTGVIWKXOXRWVVXTZQ[L[", // 68 D
    "H[MPTP RW[M[MFWF", // 69 E
    "HZTPMP RM[MFWF", // 70 F
    "F[VGTFQFNGLIKKJOJRKVLXNZQ[S[VZWYWRSR", // 71 G
    "G]L[LF RLPXP RX[XF", // 72 H
    "MWR[RF", // 73 I
    "JZUFUUTXRZO[M[", // 74 J
    "G\\L[LF RX[OO RXFLR", // 75 K
    "HYW[M[MF", // 76 L
    "F^K[KFRUYFY[", // 77 M
    "G]L[LFX[XF", // 78 N
    "G]PFTFVGXIYMYTXXVZT[P[NZLXKTKMLINGPF", // 79 O
    "G\\L[LFTFVGWHXJXMWOVPTQLQ", // 80 P
    "G]Z]X\\VZSWQVOV RP[NZLXKTKMLINGPFTFVGXIYMYTXXVZT[P[", // 81 Q
    "G\\X[QQ RL[LFTFVGWHXJXMWOVPTQLQ", // 82 R
    "H\\LZO[T[VZWYXWXUWSVRTQPPNOMNLLLJMHNGPFUFXG", // 83 S
    "JZLFXF RR[RF", // 84 T
    "G]LFLWMYNZP[T[VZWYXWXF", // 85 U
    "I[KFR[YF", // 86 V
    "F^IFN[RLV[[F", // 87 W
    "H\\KFY[ RYFK[", // 88 X
    "I[RQR[ RKFRQYF", // 89 Y
    "H\\KFYFK[Y[", // 90 Z
    "KYVbQbQDVD", // 91 [
    "KYID[_", // 92 \
    "KYNbSbSDND", // 93 ]
    "LXNHREVH", // 94 ^
    "JZJ]Z]", // 95 _
    "NVPESH", // 96 `
    "I\\W[WPVNTMPMNN RWZU[P[NZMXMVNTPSUSWR", // 97 a
    "H[M[MF RMNOMSMUNVOWQWWVYUZS[O[MZ", // 98 b
    "HZVZT[P[NZMYLWLQMONNPMTMVN", // 99 c
    "I\\W[WF RWZU[Q[OZNYMWMQNOONQMUMWN", // 100 d
    "I[VZT[P[NZMXMPNNPMTMVNWPWRMT", // 101 e
    "MYOMWM RR[RISGUFWF", // 102 f
    "I\\WMW^V`UaSbPbNa RWZU[Q[OZNYMWMQNOONQMUMWN", // 103 g
    "H[M[MF RV[VPUNSMPMNNMO", // 104 h
    "MWR[RM RRFQGRHSGRFRH", // 105 i
    "MWRMR_QaObNb RRFQGRHSGRFRH", // 106 j
    "IZN[NF RPSV[ RVMNU", // 107 k
    "MXU[SZRXRF", // 108 l
    "D`I[IM RIOJNLMOMQNRPR[ RRPSNUMXMZN[P[[", // 109 m
    "I\\NMN[ RNOONQMTMVNWPW[", // 110 n
    "H[P[NZMYLWLQMONNPMSMUNVOWQWWVYUZS[P[", // 111 o
    "H[MMMb RMNOMSMUNVOWQWWVYUZS[O[MZ", // 112 p
    "I\\WMWb RWZU[Q[OZNYMWMQNOONQMUMWN", // 113 q
    "KXP[PM RPQQORNTMVM", // 114 r
    "J[NZP[T[VZWXWWVUTTQTOSNQNPONQMTMVN", // 115 s
    "MYOMWM RRFRXSZU[W[", // 116 t
    "H[VMV[ RMMMXNZP[S[UZVY", // 117 u
    "JZMMR[WM", // 118 v
    "G]JMN[RQV[ZM", // 119 w
    "IZL[WM RLMW[", // 120 x
    "JZMMR[ RWMR[P`OaMb", // 121 y
    "IZLMWML[W[", // 122 z
    "KYVcUcSbR`RVQTOSQRRPRFSDUCVC", // 123 {
    "H\\RbRD", // 124 |
    "KYNcOcQbR`RVSTUSSRRPRFQDOCNC", // 125 }
    "KZMSNRPQTSVRWQ", // 126 ~
];
